# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build deepImageJ.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compile deepImageJ.js
        run: bash compile-js.sh
      - uses: meeDamian/github-release@2.0
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "2.0.1"
          name: deepImageJ.js
          files: dist/plugins/DeepImageJ_JS_-2.0.1-SNAPSHOT.jar
          allow_override: true